server:
  port: 8888
#Actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
spring:
  application:
    name: spring-config-server
#  profiles:
#    active: native
  cloud:
    config:
     server:
       git:
        uri: https://github.com/pedrolls/config-server.git
        search-paths: 'greeting-service'
      #caso precise autenticacao
#      username:
#      password: